### ISSUE TITLE
Not being able to query the ntdll information means automatically that the vulnerability exists?

### ISSUE THREAD

**Issue by ader1990** [ionescu007/SpecuCheck#10]
I tried to run the binary on a Windows 8.1 and 10 x64 (also compiled it myself) and it is failing with the error:
Your system either does not have the appropriate patch, or it may not support the information class required.

At line: https://github.com/ionescu007/SpecuCheck/blob/master/specucheck.c#L225
the query fails with error code -3.

From where can you deduce with certainty that the vulnerability is there? From the fact that all Windows versions had all the vulnerabilities?

If so, the code stops at the first check. Isn't it possible that the second vulnerability has been patched already? In this case, wouldn't be better to have the result for the second check if the first one failed?

Thank you,
Adrian Vladu

**Comment by ionescu007** [comment]
Hi Adrian,

This is not a Windows vulnerability, it's a CPU vulnerability. As such, all
unpatched versions of Windows are vulnerable. Additionally, both
information classes were added at the same time, so it would be unlikely
for one class to exist but not the other.

Please use Microsoft's provided PowerShell script for authoritatively
determining your patch level, it supports more features and also provides
guidance -- thanks!

Best regards,
Alex Ionescu

**Comment by nshalabi** [comment]
https://twitter.com/nader_shalabi/status/949645248715804673

**Comment by ader1990** [comment]
Thanks for the info and the tool.

Regards,
Adrian Vladu

**Comment by nshalabi** [comment]
Apologies, I removed the tweet and decided to post it as a question instead:
https://gallery.technet.microsoft.com/scriptcenter/Speculation-Control-e36f0050/view/Discussions#43922
