### ISSUE TITLE
Use under Wine on MacOS?

### ISSUE THREAD

**Issue by yyzguy** [ionescu007/SpecuCheck#18]
Will this work on under wine on MacOS ?

**Comment by yyzguy** [comment]
I mean, yes it does run under wine, but not sure how to interpret the results:

- Your system either does not have the appropriate patch, or it may not support the information class required.-

Would it be able to detect a fixed processor under Wine, or does this mean it can't get the needed information?

**Comment by ionescu007** [comment]
Wine does not implement these APIs. Sorry :(
