### ISSUE TITLE
No PCID/INVPCID support on a CPU that has these features

### ISSUE THREAD

**Issue by monk-time** [ionescu007/SpecuCheck#7]
I apologize if this is the wrong place to ask this, I don't know where else to go with this question.

For me on W7x64 with i7-4710HQ your very helpful utility shows that Kernel VA Shadowing is enabled with no PCID/INVPCID support:
```
[-] Kernel VA Shadowing Enabled:                    yes
 ├───> with User Pages Marked Global:               yes
 ├───> with PCID Support:                            no
 └───> with INVPCID Support:                         no
```

But according to a HWiNFO report on my PC and also [other resources](http://www.cpu-world.com/CPUs/Core_i7/Intel-Core%20i7-4710HQ%20Mobile%20processor.html) I can see that both these features are supported on my CPU. 

Is it just a case of MS focusing their resources atm on fully supporting modern processors in their patches, or is there no hope that a later update would extend these KVAS optimizations for older CPUs?

**Comment by ionescu007** [comment]
Hi!

Unfortunately Windows 7 would probably require too many changes to its memory management support routines to add PCID/INVPCID support. If you update to Windows 10, it should be able to fully take advantage of your processor.

**Comment by monk-time** [comment]
Gotcha, so it's a general Win7 limitation. I am relieved to hear that it's not something on my end. Thank you!
