### ISSUE TITLE
Not legacy for me ;)

### ISSUE THREAD

**Issue by greatquux** [ionescu007/SpecuCheck#9]
This is not an issue - rather I wanted to say that this project is useful even beyond Microsoft's officially supported PowerShell modules, as Install-Module requires at least PowerShell 3.0 which not all of my Window servers support, so this EXE provides a nice method to check the status without having to worry about incompatibilities if I install WMF 3.0 or higher. Thank you for it! ;)

**Comment by keithzg** [comment]
Similarly, I've actually yet to find a PC at work that Microsoft's instructions actually work on!
